# config/routes.yaml
404:
  path:          /404
  controller:    Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template:  'static/404.html.twig'
    maxAge:    86400
    sharedAge: 86400
